version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.7.0
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
      - 9201:9201
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data

volumes:
  kibana-data:
  elasticsearch-data:
