version: '3.9'
services:
  mongo:
    image: mongo:4.4@sha256:90e9402437d0fafc818fde2cc108ccb445e02b0c85b230bcf3a55def0f0029ec
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db/

  mongo-express:
    image: mongo-express:0.54@sha256:effdf4c7665bbcbdd72adcb0b074c7f29583affb6eb37e2deea284c1a4400bda
    ports:
      - 5051:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    volumes:
      - mongo-data:/data/db/

volumes:
  mongo-data:
