version: '3.9'
services:
   pgvector:
     image: ankane/pgvector@sha256:d3a9d8ac27bb7e05e333ef25b634d2625adaa85336ab729954b9e94859bf6fa7
     ports:
     -  5432:5432
     environment:
       POSTGRES_USER: username
       POSTGRES_PASSWORD: password
     volumes:
     - postgres-pgvector-data:/var/lib/postgresql/data/

volumes:
  postgres-pgvector-data:
