version: '3.9'
services:
  s3:
    image: minio/minio:RELEASE.2023-04-20T17-56-55Z
    volumes:
      - s3_data:/data
    ports:
      - "7070:9000"
      - "7071:9001"
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
      MINIO_BROWSER: "on"
      MINIO_BROWSER_PORT: 9001
      MINIO_BROWSER_DEFAULT_ROOT_OBJECT: "my-bucket"
    command: server /data --console-address ":9001"

volumes:
  s3_data:
