version: '3.9'
services:
  v2raya:
    image: mzz2017/v2raya@sha256:e7e5b846663b0df025d8d2af20cece38306e1efdde0428d34cf5041ac02bfa1a
    volumes:
      - /etc/v2raya:/etc/v2raya
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      # admin port
      - 2017:2017
      # socks port
      - 8118:9999 
      # http port
      - 9999:8118
    environment:
      V2RAYA_ADDRESS: 0.0.0.0:2017
